#!/bin/sh
killall polybar

bar="$XDG_CONFIG_HOME/polybar/bars/basic.ini bar"

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload --config=$bar > /dev/null &
  done
else
  polybar -q --reload --config=$bar > /dev/null &
fi

# Run the bars

#BAR_NAME=main
#
#IFS=$'\n'
#
#for item in $(polybar --list-monitors); do
#    MONITOR=$(echo $item | cut -d" " -f1 | cut -d":" -f1)
#    IS_PRIMARY=$(echo $item | cut -d" " -f3)
#    if [[ $IS_PRIMARY == *"primary"* ]]; then
#        TRAY_POSITION=right MONITOR=$MONITOR polybar --reload $BAR_NAME &
#    else
#        MONITOR=$MONITOR polybar --reload $BAR_NAME &
#    fi
#done
