#!/bin/sh

[ "$1" = "posix" ] && cmd="export \1=\3"
[ "$1" = "fish" ] && cmd="set -x \1 \3"

# todo: doppelte einträge mit sed
sed "s/\s*#.*//g; /^\s*$/ d; s/\([^ ]*\)\(\s*\)\(.*\)/$cmd/p" $HOME/.config/dotfiles/envvars | sort -u
