#!/bin/sh

[ "$1" = "posix" ] && cmd="alias \1='\3'"
[ "$1" = "fish" ] && cmd="abbr \1 '\3'"
[ "$1" = "zsh" ] && cmd="\1=\3"

# todo: doppelte einträge mit sed
sed "s/\s*#.*//g; /^\s*$/ d; s/\([^ ]*\)\(\s*\)\(.*\)/$cmd/p" "$HOME/.config/dotfiles/abbr" | sort -u
